#!/usr/bin/env zsh

# Run this whenever you change `trigger` or `apps`, then reload skhd.

set -euo pipefail

trigger="ctrl + cmd"

typeset -A apps=(
  b 'open -a "Safari"'
  f 'open -a "Finder"'
  s 'open -a "Slack"'
  x 'open -b com.apple.dt.Xcode'
  t 'open -a "Ghostty"'
  n 'open -a "Notion"'
  0x1E 'open ~/Documents/Pictures/Screenshots' # 0x1E = ] on US ANSI; skhd needs hex keycode for punctuation
)

out="${0:A:h}/skhdrc"

{
  echo "# AUTO-GENERATED by gen-skhdrc.sh — edit that script, not this file."
  echo ""
  for letter in "${(@k)apps}"; do
    printf '%s - %s : %s\n' "$trigger" "$letter" "${apps[$letter]}"
  done | sort
} >"$out"

echo "Wrote $out"

if command -v skhd >/dev/null && pgrep -x skhd >/dev/null; then
  skhd --restart-service
  echo "Restarted skhd"
fi
